PAPER_EXTRACTION_SCHEMA = {
    "title": "paper_extraction",
    "type": "object",
    "properties": {
        "paper_id": {"type": "string"},
        "filename": {"type": "string"},
        "bibtex_key": {"type": ["string", "null"]},
        "title": {"type": "string"},
        "authors": {"type": "array", "items": {"type": "string"}},
        "year": {"type": ["integer", "null"]},
        "venue": {"type": ["string", "null"]},
        "method_name": {"type": ["string", "null"]},
        "annotation_setting": {"type": "string"},
        "scribble_protocol": {"type": "string"},
        "task_domain": {"type": "string"},
        "modality": {"type": "array", "items": {"type": "string"}},
        "segmentation_target": {"type": "array", "items": {"type": "string"}},
        "core_problem": {"type": "string"},
        "key_contributions": {"type": "array", "items": {"type": "string"}},
        "method_summary": {"type": "string"},
        "algorithm_steps": {"type": "array", "items": {"type": "string"}},
        "method_components": {
            "type": "object",
            "properties": {
                "backbone": {"type": ["string", "null"]},
                "architecture": {"type": "array", "items": {"type": "string"}},
                "modules": {"type": "array", "items": {"type": "string"}},
                "loss_terms": {"type": "array", "items": {"type": "string"}},
                "pseudo_label_generation": {"type": ["string", "null"]},
                "consistency_target": {"type": ["string", "null"]},
                "reliability_mechanism": {"type": ["string", "null"]},
                "prior_type": {"type": ["string", "null"]},
            },
            "required": ["architecture", "modules", "loss_terms"],
        },
        "taxonomy_signals": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "signal": {"type": "string"},
                    "present": {"type": "boolean"},
                    "strength": {"type": "string"},
                    "reason": {"type": "string"},
                    "evidence_ids": {"type": "array", "items": {"type": "string"}},
                },
                "required": ["signal", "present", "strength", "reason", "evidence_ids"],
            },
        },
        "datasets": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "dataset_name": {"type": "string"},
                    "role": {"type": "string"},
                    "modality": {"type": ["string", "null"]},
                    "target": {"type": ["string", "null"]},
                    "cases_or_images": {"type": ["string", "null"]},
                    "dimensionality": {"type": "string"},
                    "num_classes": {"type": ["string", "null"]},
                    "split_protocol": {"type": ["string", "null"]},
                    "scribble_protocol": {"type": ["string", "null"]},
                    "metrics": {"type": "array", "items": {"type": "string"}},
                    "results_summary": {"type": ["string", "null"]},
                    "evidence_ids": {"type": "array", "items": {"type": "string"}},
                },
                "required": ["dataset_name", "role", "dimensionality", "metrics", "evidence_ids"],
            },
        },
        "metrics": {"type": "array", "items": {"type": "string"}},
        "baselines": {"type": "array", "items": {"type": "string"}},
        "limitations": {"type": "array", "items": {"type": "string"}},
        "boundary_case_notes": {"type": "array", "items": {"type": "string"}},
        "evidence_spans": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "evidence_id": {"type": "string"},
                    "paper_id": {"type": "string"},
                    "section": {"type": ["string", "null"]},
                    "page": {"type": ["integer", "null"]},
                    "text": {"type": "string"},
                    "paraphrase": {"type": "string"},
                    "supports_fields": {"type": "array", "items": {"type": "string"}},
                },
                "required": ["evidence_id", "paper_id", "text", "paraphrase", "supports_fields"],
            },
        },
        "extraction_confidence": {"type": "number"},
    },
    "required": [
        "paper_id",
        "filename",
        "title",
        "authors",
        "annotation_setting",
        "scribble_protocol",
        "task_domain",
        "modality",
        "segmentation_target",
        "core_problem",
        "key_contributions",
        "method_summary",
        "algorithm_steps",
        "method_components",
        "taxonomy_signals",
        "datasets",
        "metrics",
        "baselines",
        "limitations",
        "boundary_case_notes",
        "evidence_spans",
        "extraction_confidence",
    ],
}
